version: "3.7"
services:

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5739


  app:
    build:
      context: .
    env_file:
      - config.py
    container_name: app
    ports:
      - 9999:8000
    depends_on:
      - redis

  celery:
    build:
      context: .
    env_file:
      - config.py
    container_name: celery_app
    depends_on:
      - redis

#  flower:
#    build:
#      context: .
#    env_file:
#      - config.py
#    container_name: flower_app
#    depends_on:
#      - redis
#      - celery
#    ports:
#      - 8888:5555

